### PR TITLE
Update for Ink@0.2.x

### PR DESCRIPTION
**Pull request by vadimdemedes**
Ink@0.2.1 has just been released and it contains breaking changes. See https://github.com/vadimdemedes/ink/releases for more info.

PR updates this component for the latest Ink and contains some important fixes, like moving `ink` to `devDependencies`.

### CODE REVIEW

**Comment by brigand** [comment]
Thanks!

`process.stdout.columns` can change, right? Best to do that in render at least, if we don't subscribe to it in some way.

**Comment by vadimdemedes** [comment]
Good point!

**Comment by vadimdemedes** [comment]
Fixed.

**Comment by brigand** [comment]
Thanks! 2.0.0

**Pull request merged**
